networks:
  backend:
services:
  go:
    build: ./go
    tty: true
    ports:
      - "7777:7777"
    depends_on:
      - firebase
    volumes:
      - ./go/app:/go/src/app
  firebase:
    build:
      context: ./firebase
    volumes:
      - ./firebase/emulators/:/opt/workspace:cached
      - ./firebase/bin/:/root/.cache:cached
      - ./firebase/config/:/root/.config:cached
    ports:
      - 4000:4000 # Emulator Suite UI
      - 5000:5000 # Firebase Hosting
      - 5001:5001 # Clound Functions
      - 9000:9000 # Realtime Database
      - 8080:8080 # Cloud Firestore
      - 8085:8085 # Cloud Pub/Sub
    working_dir: /opt/workspace
    networks:
      - backend
    command: bash
    tty: true