networks:
  backend:
services:
  go:
    build: ./go
    tty: true
    ports:
      - "7777:7777"
    depends_on:
      - pubsub
    volumes:
      - ./go/app:/go/src/app
  ruby:
    build: ./ruby
    volumes:
      - ./ruby:/app
  protoc:
    build: ./protoc
    volumes:
      - ./protoc:/protoc
      - ./go/app/eggplant/pb:/protoc/pb/go
      - ./ruby/src/pb:/protoc/pb/rb
  pubsub:
    build: ./pubsub
    restart: always
    platform: linux/amd64
    environment:
      - PUBSUB_PROJECT_ID=eggplant-project
      - PUBSUB_TOPIC_ID=eggplant-topic
      - PUBSUB_SUBSCRIPTION_ID=eggplant-subscription
      - PUBSUB_EMULATOR_HOST=0.0.0.0:8085
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ./pubsub:/code
    command:
      ./pubsub/entrypoint.sh
    ports:
      - 8085:8085